### ISSUE TITLE
[BUG] Summons Not Working: "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by arthurfferreira** [arbron/fvtt-summoner#58]
**Describe the bug**
No summoning spell or ability works. The developer's tools console log shows the following error:

```
summons-actor.mjs:214 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at SummonsActor._cleanRollData (summons-actor.mjs:214:23)
    at SummonsActor._cleanRollData (summons-actor.mjs:221:6)
    at SummonsActor._cleanRollData (summons-actor.mjs:221:6)
    at SummonsActor._cleanRollData (summons-actor.mjs:221:6)
    at SummonsActor._cleanRollData (summons-actor.mjs:221:6)
    at SummonsActor._cleanRollData (summons-actor.mjs:221:6)
(...skipping a huge amount of lines...)
    at SummonsActor._cleanRollData (summons-actor.mjs:221:6)
    at SummonsActor._cleanRollData (summons-actor.mjs:221:6)
    at SummonsActor._cleanRollData (summons-actor.mjs:221:6)
    at Actor5e.getChanges (summons-actor.mjs:114:35)
    at summon (summon.mjs:53:1)
``` 

**To Reproduce**
1. Open the browser's developer's tool to see the console output
2. Use any spell/ability following the instructions
4. See error in the console

**Expected behavior**
The summon to be placed in the canvas

**Screenshots**
<img width="730" alt="image" src="https://github.com/arbron/fvtt-summoner/assets/840707/3e926e7c-f9c8-4155-9d65-ae7d8eb7b08e">

**Environment:**
 - Foundry Core Version: 0.12.325
 - Module Version: 1.1.6
 - Host: self hosted in Oracle Cloud (Linux)
 - OS: Tested on MacOS, Windows and Fedora 
 - Browser: Tested with the latest versions of Google Chrome, Microsoft Edge and Mozilla Firefox

**Comment by arbron** [comment]
Warpgate doesn't support V12 and has ceased development, plus all of the module features have been integrated into the DnD 5e system, so there will be no V12-compatible version of the module.
